name: Dominic St-Pierre
description: Dominic St-Pierre's Blog
url: http://dstpierre.github.io
markdown: redcarpet
pygments: false
safe: true
permalink: pretty
author: Dominic St-Pierre
email: dominicstpierre@gmail.com