name: Dominic St-Pierre
description: Dominic St-Pierre's Blog
markdown: redcarpet
timezone: America/Montreal
permalink: /:year/:month/:title.html
url: http://www.dominicstpierre.com
safe: true
author: Dominic St-Pierre
email: dominicstpierre@gmail.com
highlighter: rouge