name: Dominic St-Pierre
description: Dominic St-Pierre's Blog
markdown: redcarpet
timezone: America/Montreal
permalink: /:year/:month/:title.html
url: http://dstpierre.github.io
markdown: redcarpet
pygments: false
safe: true
author: Dominic St-Pierre
email: dominicstpierre@gmail.com
